spring:
  datasource:
    url: jdbc:postgresql://ep-gentle-heart-a1h2uztb-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_ma46uYwTPKJg&sslmode=require
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: ${PORT}